import Providers from '@/components/providers/Provider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AuthProvider } from '@/components/providers/AuthProvider';
import GlobalNavigation from '@/components/GlobalNavigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <AuthProvider>
            <div className='flex flex-col min-h-screen w-screen'>
              <GlobalNavigation />
              {children}
            </div>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
