name: ci

on: [issue_comment, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Node v # Node v 확인
        run: node -v
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
          API_KEY: ${{ secrets.API_KEY }}}
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn
      - run: yarn run ci
      # TODO
      # - name: Publish code coverage
      #   uses: paambaati/codeclimate-action@v3.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: a60db4c3f80565cbce10b5bad84a0667ee1489817907743658bf19c84be30c8f
