name: Cypress Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Start Next.js App
        run: npm run start &

      - name: Wait for Next.js App to Start
        run: sleep 20

      - name: Run Cypress Tests
        run: npx cypress run
