name: (PROD) Deploy with tag

run-name: Deploy ${{ inputs.tag }} by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy.'
        type: string
        required: true
